

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      - "8123:8123"


  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_homeassistant
    restart: unless-stopped
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "1883:1883"
  

